build:
    environment:
        php:
            version: 7.3
            version: 7.4
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
checks:
    php:
        code_rating: true
filter:
    excluded_paths:
        - 'tests/'
